blank_issues_enabled: false
contact_links:
  - name: ğŸ’¡ Feature request
    url: https://github.com/orgs/iptv-org/discussions/categories/ideas
    about: For any ideas or feature requests
  - name: â“ Q&A
    url: https://github.com/orgs/iptv-org/discussions/categories/q-a
    about: Ask the community for help
