blank_issues_enabled: false
contact_links:
  - name: ğŸ” Looking for a channel
    url: https://github.com/orgs/iptv-org/discussions/new/choose
    about: Need help finding a link to a channel stream
  - name: ğŸ’¡ Feature request
    url: https://github.com/orgs/iptv-org/discussions/new/choose
    about: For any ideas or feature requests
  - name: â“ Ask a question
    url: https://github.com/orgs/iptv-org/discussions/new/choose
    about: Ask questions about this project
