blank_issues_enabled: false
contact_links:
  - name: ğŸ’¡ Feature Request
    url: https://github.com/iptv-org/iptv/discussions/new
    about: For any ideas or feature requests
  - name: â“ Ask a Question
    url: https://github.com/iptv-org/iptv/discussions/new
    about: Ask questions about this project
