blank_issues_enabled: true
contact_links:
  - name: ğŸ’¡ Feature request
    url: https://github.com/orgs/iptv-org/discussions/categories/ideas
    about: For any ideas or feature requests
  - name: â“ Ask a question
    url: https://github.com/orgs/iptv-org/discussions/categories/q-a
    about: Ask questions about this project
