name: Generate index.m3u

on:
  push:
    branches:
      - master  # Run on pushes to the master branch
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use the latest Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run script to generate index.m3u
        run: |
          echo "import os" > ums.py
          echo "" >> ums.py
          echo "# Define base URL for the GitHub raw content" >> ums.py
          echo "base_url = 'https://raw.githubusercontent.com/ums91/umsiptv/master/streams/'" >> ums.py
          echo "index_file_path = 'streams/index.m3u'" >> ums.py
          echo "" >> ums.py
          echo "# Get list of all .m3u files in streams directory" >> ums.py
          echo "m3u_files = [f for f in os.listdir('streams') if f.endswith('.m3u')]" >> ums.py
          echo "" >> generate_index.py
          echo "# Write to index.m3u file" >> generate_index.py
          echo "with open(index_file_path, 'w') as index_file:" >> ums.py
          echo "    index_file.write('#EXTM3U\\n')" >> ums.py
          echo "    for m3u_file in m3u_files:" >> ums.py
          echo "        index_file.write(f'#EXTINF:-1, {m3u_file.split('.')[0].capitalize()} Playlist\\n')" >> ums.py
          echo "        index_file.write(f'{base_url}{m3u_file}\\n')" >> ums.py
          echo "        with open(os.path.join('streams', m3u_file), 'r') as f:" >> ums.py
          echo "            content = f.read()" >> ums.py
          echo "            index_file.write(content)" >> ums.py
          echo "            index_file.write('\\n')" >> ums.py
          echo "" >> ums.py
          echo "print('index.m3u has been created with all .m3u file links and content.')" >> ums.py

          python ums.py

      - name: Commit and push changes
        run: |
          git config --global user.email "omargoroo91@gmail.com"
          git config --global user.name "ums91"
          git add streams/index.m3u
          git commit -m "Update index.m3u with all .m3u file links and content" || echo "No changes to commit"
          git push
